name: Build OpenJDK 21 for Android and iOS

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 */2 *'

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with CI build script
      run: bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk21-${{matrix.arch}}"
        path: jdk21*.tar.xz
    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre21-${{matrix.arch}}'
        path: jre21*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre21-debuginfo-${{matrix.arch}}"
        path: dizout

  build_iosport:
    name: "Build for iOS aarch64"
    runs-on: MacStadium
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with CI build script
      run: |
        export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
        export BUILD_IOS=1
        bash "ci_build_arch_aarch64.sh"

    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk21-ios-aarch64"
        path: jdk21*.tar.xz

    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre21-ios-aarch64'
        path: jre21*.tar.xz

    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre21-ios-debuginfo-aarch64"
        path: dizout

  pojav:
    needs: build_android
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get jre21-aarch32
      uses: actions/download-artifact@v2
      with:
        name: jre21-aarch32
        path: pojav
    - name: Get jre21-aarch64
      uses: actions/download-artifact@v2
      with:
        name: jre21-aarch64
        path: pojav
    - name: Get jre21-x86
      uses: actions/download-artifact@v2
      with:
        name: jre21-x86
        path: pojav
    - name: Get jre21-x86_64
      uses: actions/download-artifact@v2
      with:
        name: jre21-x86_64
        path: pojav
    - name: Repack JRE
      run: bash "repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre21-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: jre21-pojav
          path: pojav/jre21-pojav/*
